// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDchhfYNUUQLfa74cKK0LgxQS1cyK_2uIc',
    appId: '1:1062697221169:web:2b477c465c146ad7272910',
    messagingSenderId: '1062697221169',
    projectId: 'chefmate-af728',
    authDomain: 'chefmate-af728.firebaseapp.com',
    storageBucket: 'chefmate-af728.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzTViO4cy9PHeeVPtDyrqnTJgjf-zh5H4',
    appId: '1:1062697221169:android:480063fd2de95c4f272910',
    messagingSenderId: '1062697221169',
    projectId: 'chefmate-af728',
    storageBucket: 'chefmate-af728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YTmSNLL-VDE6vGvZdMCR1Jm8oSP-Wxw',
    appId: '1:1062697221169:ios:c75a9e0cbff8f2dd272910',
    messagingSenderId: '1062697221169',
    projectId: 'chefmate-af728',
    storageBucket: 'chefmate-af728.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8YTmSNLL-VDE6vGvZdMCR1Jm8oSP-Wxw',
    appId: '1:1062697221169:ios:c75a9e0cbff8f2dd272910',
    messagingSenderId: '1062697221169',
    projectId: 'chefmate-af728',
    storageBucket: 'chefmate-af728.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDchhfYNUUQLfa74cKK0LgxQS1cyK_2uIc',
    appId: '1:1062697221169:web:294dcfb61a4a49ff272910',
    messagingSenderId: '1062697221169',
    projectId: 'chefmate-af728',
    authDomain: 'chefmate-af728.firebaseapp.com',
    storageBucket: 'chefmate-af728.firebasestorage.app',
  );
}
