// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:food_app/core/model/food_model/meals.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MealAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MealAdapter());
  }
}
